# Generated by Django 4.1.2 on 2022-10-28 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblbateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblnodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('sector', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tblred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('gateway', models.CharField(max_length=20)),
                ('mascara', models.CharField(max_length=15)),
                ('ip_zona', models.CharField(max_length=12)),
                ('nodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo.tblnodo')),
            ],
        ),
        migrations.CreateModel(
            name='tblsensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('descripcion', models.CharField(max_length=200)),
                ('bateria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo.tblbateria')),
                ('red', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo.tblred')),
            ],
        ),
        migrations.CreateModel(
            name='tbltipo_sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('detalle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tblubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.CharField(max_length=80)),
                ('longitud', models.CharField(max_length=80)),
                ('referencia', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='DB_monitoreo',
        ),
        migrations.AddField(
            model_name='tblsensor',
            name='tip_sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo.tbltipo_sensor'),
        ),
        migrations.AddField(
            model_name='tblsensor',
            name='ubicaciones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo.tblubicacion'),
        ),
    ]
