# Generated by Django 4.1.2 on 2022-11-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0002_tblbateria_tblnodo_tblred_tblsensor_tbltipo_sensor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblsensor',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
