# Generated by Django 4.1.2 on 2022-11-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0003_alter_tblsensor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblsensore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=6)),
                ('descripcion', models.CharField(max_length=200)),
                ('nivel_bateria', models.IntegerField()),
                ('estado_bateria', models.BooleanField(default=True)),
                ('tipo_sensor', models.CharField(max_length=100)),
                ('detalle_sensor', models.CharField(max_length=200)),
                ('latitud_ubicacion', models.CharField(max_length=80)),
                ('longitud_ubicacion', models.CharField(max_length=80)),
                ('referencia_ubicacion', models.CharField(max_length=200)),
                ('ip_red', models.CharField(max_length=15)),
                ('gateway_red', models.CharField(max_length=20)),
                ('mascara_red', models.CharField(max_length=15)),
                ('ip_zona_red', models.CharField(max_length=12)),
                ('descripcion_nodo', models.CharField(max_length=200)),
                ('sector_nodo', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='tblred',
            name='nodo',
        ),
        migrations.RemoveField(
            model_name='tblsensor',
            name='bateria',
        ),
        migrations.RemoveField(
            model_name='tblsensor',
            name='red',
        ),
        migrations.RemoveField(
            model_name='tblsensor',
            name='tip_sensor',
        ),
        migrations.RemoveField(
            model_name='tblsensor',
            name='ubicaciones',
        ),
        migrations.DeleteModel(
            name='tblbateria',
        ),
        migrations.DeleteModel(
            name='tblnodo',
        ),
        migrations.DeleteModel(
            name='tblred',
        ),
        migrations.DeleteModel(
            name='tblsensor',
        ),
        migrations.DeleteModel(
            name='tbltipo_sensor',
        ),
        migrations.DeleteModel(
            name='tblubicacion',
        ),
    ]
